#!/bin/sh

set -e
umask 0002

OPTIONS="--rename name --fqdn name --polar disabled --required --user local-owner --url-path-absolute source --hostname target --select-base /usr/libexec/device/timers/backup/rsync/frequency.txt --select frequency --relation-base /etc/device/timers/backup/host --relation-name name --relation-suffix .txt --relation host"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart backup-rsync-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

