#!/bin/sh

set -e
umask 0002

OPTIONS="--show name \
         --fqdn name \
         --show-flags disabled,substate,state,status \
         --polar sparse \
         --integer-minimum 1 --integer-maximum 2700000 --integer timestamp \
         --show-table name,host,local-owner,source,target,frequency,sparse,timestamp \
         --flag ⚫ --polar disabled \
         --flag 🔴 --flag-description retrying --flag-match auto-restart --systemd-parameter SubState --systemd-name name --systemd-prefix backup-rsync@ --systemd-service substate \
         --flag 🟢 --flag-description running --flag-match ^active$ --systemd-name name --systemd-prefix backup-rsync@ --systemd-service state \
         --flag 🟡 --flag-description stale --flag-match stale --systemd-parameter StatusText --systemd-name name --systemd-prefix backup-rsync@ --systemd-service status \
         --text includes \
         --required \
         --user local-owner \
         --url-path-absolute source \
         --hostname target \
         --select-base /usr/libexec/device/timers/backup/rsync/frequency.txt --select frequency \
         --relation-base /etc/device/timers/backup/host --relation-name name --relation-suffix .txt --relation host"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

