#!/bin/sh

set -e
umask 0002

OPTIONS="--show name \
         --fqdn name \
         --show-flags disabled,substate,state \
         --show-table name,host,local-owner,frequency,backup-files \
         --flag X --polar disabled \
         --flag + --flag-description retrying --flag-match auto-restart --systemd-parameter SubState --systemd-name name --systemd-prefix backup-routeros@ --systemd-service substate \
         --flag R --flag-description running --flag-match ^active$ --systemd-name name --systemd-prefix backup-routeros@ --systemd-service state \
         --systemd-parameter StatusText --systemd-name name --systemd-prefix backup-routeros@ --systemd-service status \
         --polar backup-files \
         --required \
         --user local-owner \
         --select-base /usr/libexec/device/timers/backup/routeros/frequency.txt --select frequency \
         --relation-base /etc/device/timers/backup/host --relation-name name --relation-suffix .txt --relation host"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

