#!/bin/sh

set -e
umask 0002

OPTIONS="--rename name --fqdn name --polar disabled --required --user local-owner --relation-base /etc/device/timers/backup/host --relation-name name --relation-suffix .txt --relation host --select-base /usr/libexec/device/timers/backup/libvirt/frequency.txt --select frequency"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart backup-libvirt-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

